export enum Configuration {
  API_PORT = 'API_PORT',

  DB_TYPE = 'DB_TYPE',
  DB_PORT = 'DB_PORT',
  DB_HOST = 'DB_HOST',
  DB_USERNAME = 'DB_USERNAME',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_DATABASE = 'DB_DATABASE',
}
